// AUTO-GENERATED FILE. DO NOT EDIT.
// Source: src/assets/content/glossary.json
// Generated by: npm run bundle-data

export const GLOSSARY_DATA: unknown = [
  {
    "id": "encumbrance",
    "term": "Encumbrance",
    "definition": "Funds committed for a future expenditure but not yet disbursed."
  },
  {
    "id": "appropriation",
    "term": "Appropriation",
    "definition": "Legislative authorization to spend public funds for a specified purpose."
  },
  {
    "id": "fund-balance",
    "term": "Fund Balance",
    "definition": "Difference between governmental fund assets and liabilities available for appropriation."
  }
];
