// AUTO-GENERATED FILE. DO NOT EDIT.
// Source: src/assets/content/sop.json
// Generated by: npm run bundle-data

export const SOP_DATA: unknown = [
  {
    "id": "new-module",
    "title": "LEarning to Play",
    "category": "pitfall",
    "content": [
      {
        "type": "text",
        "value": "Igniore all "
      },
      {
        "type": "term",
        "termId": "appropriation",
        "display": "Appropriation"
      },
      {
        "type": "text",
        "value": "\n"
      },
      {
        "type": "image",
        "src": "assets/images/Rick-Astley.jpg",
        "alt": "Rick Astley"
      },
      {
        "type": "text",
        "value": "\nNever gonna give you up"
      }
    ],
    "children": [
      {
        "id": "new-child",
        "title": "New child",
        "category": "routine",
        "content": [
          {
            "type": "text",
            "value": " faslkdf jawlkejf lkawjef "
          }
        ],
        "children": [],
        "version": "1.0",
        "updatedAt": "2026-03-30"
      }
    ],
    "version": "1.0",
    "updatedAt": "2026-03-30"
  }
];
