// AUTO-GENERATED FILE. DO NOT EDIT.
// Source: src/assets/content/sop.json
// Generated by: npm run bundle-data

export const SOP_DATA: unknown = [
  {
    "id": "new-module",
    "title": "Template Root Name",
    "category": "routine",
    "content": [
      {
        "type": "text",
        "value": "Insert glossary terms as follows "
      },
      {
        "type": "term",
        "termId": "appropriation",
        "display": "Appropriation"
      },
      {
        "type": "text",
        "value": "\n\nImages can be inserted inline and uploaded in the editor\n"
      },
      {
        "type": "image",
        "src": "assets/images/Rick-Astley.jpg",
        "alt": "Rick Astley"
      },
      {
        "type": "text",
        "value": "\nNever gonna give you up"
      }
    ],
    "children": [
      {
        "id": "new-child",
        "title": "Template Child",
        "category": "one-off",
        "content": [
          {
            "type": "text",
            "value": "Adding a child will nest the content into the root without "
          },
          {
            "type": "term",
            "termId": "encumbrance",
            "display": "Encumbrance"
          }
        ],
        "children": [],
        "version": "1.0",
        "updatedAt": "2026-03-30"
      }
    ],
    "version": "1.0",
    "updatedAt": "2026-03-30"
  }
];
