// AUTO-GENERATED FILE. DO NOT EDIT.
// Source: src/assets/content/sop.json
// Generated by: npm run bundle-data

export const SOP_DATA: unknown = [
  {
    "id": "new-module",
    "title": "LEarning to Play",
    "category": "pitfall",
    "content": [
      {
        "type": "text",
        "value": "Igniore all "
      }
    ],
    "children": [],
    "version": "1.0",
    "updatedAt": "2026-03-30"
  }
];
