// AUTO-GENERATED FILE. DO NOT EDIT.
// Source: src/assets/content/workspace-config-presets.json
// Generated by: npm run bundle-data

export const WORKSPACE_CONFIG_PRESETS_DATA: unknown = [
  {
    "id": "budget-planning-core",
    "label": "Budget Planning Core",
    "moduleIds": [
      "annual-budget-cycle",
      "department-requests"
    ]
  },
  {
    "id": "risk-and-recovery",
    "label": "Risk and Recovery",
    "moduleIds": [
      "encumbrance-closeout-pitfalls",
      "midyear-revenue-collapse"
    ]
  }
];
